apiVersion : apps/v1
kind: Deployment
metadata:
  name: dariapavlovarakutentask 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dariapavlovarakutentask
  template:
    metadata:
      labels:
        app: dariapavlovarakutentask 
    spec:
      containers:
        - name: dariapavlovarakutentask 
          image: franksregisty.azurecr.io/dariapavlovarakutentask
          ports:
          - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
    name: dariapavlovarakutentask
spec:
    type: LoadBalancer
    ports:
    - port: 5000 
    selector:
        app: dariapavlovarakutentask