name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag python-docker:$(date +%s)
    - name: Tag Image
      run: docker tag python-docker:$(date +%s) ${{secrets.DOCKER_USER}}/python-docker:$(date +%s)
    - name: Login to DockerHub
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Push to DockerHub
      run: docker push ${{secrets.DOCKER_USER}}/python-docker:$(date +%s)