name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag python-docker:v2
    - name: Tag Image
      run: docker tag python-docker:v2 franksword/python-docker:v2
    - name: Login to DockerHub
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Push to DockerHub
      run: docker push franksword/python-docker:v2