name: Docker Image CI

on:
  pull_request:
    branches: [ main ]
env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  REGISTRY: docker.io
  IMAGE_NAME: ${{ github.repository }}
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag python-docker:${GITHUB_REF##*/}-v2 --build-arg ${GITHUB_SHA} --build-arg ${GITHUB_REF##*/}
    
    - name: Tag Image
      run: docker tag python-docker:${GITHUB_REF##*/}-v2 franksword/python-docker:${GITHUB_REF##*/}-v2
    
    - name: Login to DockerHub
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    
    - name: Push to DockerHub
      run: docker push franksword/python-docker:${GITHUB_REF##*/}-v2