name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s) --build-arg GITHASH=$(git rev-parse --short "$GITHUB_SHA") GITBRANCH=${GITHUB_REF#refs/heads/}
    
